### ISSUE TITLE
An unexpected error occurred

### ISSUE THREAD

**Issue by githubsch** [mainio/c5_free_cookies_disclosure#1]
Hi, after installing the add-on (latest C5.7.5.3) we have difficulties to log-in again to our local installation. "An unexpected error occurred. File does not exist at path /Applications/MAMP/htdocs/C5-ART/packages/free_cookies_disclosure/vendor/autoload.php". 

When searching for the autoload.php file in the downloaded zip, we can't find any. Exchanging the install folder with a new one does not solve it. At present we can't log-in to our site. 

Could you give us a tip what needs to be changed ..simply removing the add folder results in more errors. (no log-in possible) We want to make it clear, we are new to concrete5. 

Many regards. (here's a screenshot)
![bildschirmfoto 2015-11-29 um 22 05 14](https://cloud.githubusercontent.com/assets/16072896/11460052/515d03d6-96e5-11e5-8a47-46b9a682deff.jpg)

**Comment by ahukkanen** [comment]
Please follow the installation instructions in the README file, it should fix this problem.

**Comment by githubsch** [comment]
Hi, thanks for the feedback. Do you mean .."Make sure you have Composer installed."? 
At present we can't do much via the gui/can't log-in. If you could provide some infos, it 
would helpful. Many regards.

**Comment by ahukkanen** [comment]
You don't need GUI for installing composer or the composer packages. Infos for installing the composer packages are basically in the add-on installation instructions. If you need help with composer, please refer to their documentation (also linked in the installation instructions).

**Comment by githubsch** [comment]
Hi Antii Hukkanen,

thanks for the reply. It is the php tool composer what we didn't install
before going any further. We thought Composer is already integrated
in Concrete5  ..it is, but not the php tool (we now know).

Installing without the GUI is something we haven't done before. So it
seems ..our road ends here.

Many regards.

**Comment by ahukkanen** [comment]
If you remove the package row from the `Packages` table you can get the add-on uninstalled. Here's the SQL you need to run manually:

```
DELETE FROM Packages WHERE pkgHandle = 'free_cookies_disclosure';
```

After that, this add-on is uninstalled.

You are not unfortunately able to install this add-on without getting familiar with composer and running it through the command line. If we ever decide to publish this to the marketplace, the required composer packages will ship with that version.
