### ISSUE TITLE
Manual deinstall/deacitvating

### ISSUE THREAD

**Issue by githubsch** [mainio/c5_free_cookies_disclosure#2]
Hi, we still seem to have issues with our concrete5 7.5.3, install 
running the add-on. Reading the instructions does not help us.

From the error message ("An unexpected error occurred. File 
does not exist at path .../packages/free_cookies_disclosure/
vendor/autoload.php") our attention leads to a vendor folder in 
the free_cookies_disclosure add-ons folder itself. In our C5 7.5.3 
install we see a "vendor" folder holding a "autoload.php"inside 
the concrete folder.

That's all we are able to find out ourselves at present. 

Regards

**Comment by githubsch** [comment]
##

**Comment by ahukkanen** [comment]
Please carefully read the installation instructions, I'm really 100% sure it is the problem in your case that you have missed one point. Do not continue forward from any steps before you have successfully completed that step.

From the comment above "we see a "vendor" folder holding a "autoload.php"inside 
the concrete folder" I see that you are missing or misinterpreting point `4.` in the installation instructions of this add-on.

**Comment by ahukkanen** [comment]
Adding here as well the manual uninstallation instructions (ref #1).

To manually uninstall the add-on, run the following SQL against the database that contains your concrete5 installation:

```
DELETE FROM Packages WHERE pkgHandle = 'free_cookies_disclosure';
```

**Comment by githubsch** [comment]
Thanks for the info we have just received (it did sticked in the spam 
folder)
